"""Exercise schemas adhering strictly to the CyberSoft Project Schema contract (Task 23)."""

from datetime import datetime
from typing import Any, Literal
from pydantic import BaseModel, Field, field_validator


class TestCase(BaseModel):
    """Test case specification to verify exercise solution feasibility."""

    __test__ = (
        False  # Prevent pytest from treating this Pydantic schema as a test class
    )

    id: str = Field(..., description="Mã định danh test case (vd: TC-01)")
    description: str = Field(..., description="Mục tiêu kiểm thử của test case")
    input_params: dict[str, Any] = Field(
        default_factory=dict, description="Tham số đầu vào kiểm thử"
    )
    expected_output: Any = Field(
        ..., description="Kết quả kỳ vọng (số lượng dòng, giá trị, kiểu dữ liệu)"
    )
    assertion_type: Literal[
        "row_count", "column_match", "exact_value", "contains_value", "data_type"
    ] = Field("exact_value", description="Phương thức so sánh kết quả")


class ExerciseBase(BaseModel):
    """Base fields for an exercise definition."""

    id: str = Field(..., description="Mã định danh bài tập duy nhất (vd: EX-RETAIL-01)")
    dataset_id: str = Field(
        ..., description="Mã bộ dữ liệu liên kết (vd: retail_sales_v1)"
    )
    title: str = Field(..., min_length=5, description="Tiêu đề bài tập")
    description: str = Field(..., min_length=15, description="Nội dung đề bài chi tiết")
    bloom_level: Literal[
        "Remember", "Understand", "Apply", "Analyze", "Evaluate", "Create"
    ] = Field(..., description="Cấp độ tư duy theo Thang Bloom")
    difficulty: Literal["Beginner", "Intermediate", "Advanced"] = Field(
        ..., description="Độ khó phân loại sư phạm"
    )
    exercise_type: Literal["SQL", "Python", "Data Analysis"] = Field(
        "SQL", description="Phân loại kỹ năng bài tập"
    )
    learning_outcomes: list[str] = Field(
        ...,
        min_length=1,
        description="Chuẩn đầu ra học tập (DoD bắt buộc >= 1 outcome)",
    )
    schema_dependencies: list[str] = Field(
        default_factory=list,
        description="Danh sách các cột hoặc trường dữ liệu cần sử dụng",
    )
    starter_code: str = Field("", description="Mã khung gợi ý cho học viên bắt đầu")
    solution_code: str = Field(
        ..., min_length=5, description="Mã lời giải / câu truy vấn chuẩn"
    )
    test_cases: list[TestCase] = Field(
        ...,
        min_length=1,
        description="Danh sách test cases kiểm chứng (DoD bắt buộc >= 1 test case)",
    )
    hints: list[str] = Field(
        default_factory=list, description="Gợi ý sư phạm hỗ trợ học viên"
    )

    @field_validator("learning_outcomes")
    @classmethod
    def validate_learning_outcomes(cls, v: list[str]) -> list[str]:
        if not v or len(v) == 0:
            raise ValueError(
                "Mỗi bài tập bắt buộc phải có ít nhất 1 chuẩn đầu ra (learning outcome) theo tiêu chí DoD!"
            )
        for item in v:
            if len(item.strip()) < 5:
                raise ValueError(
                    "Chuẩn đầu ra phải có độ dài tối thiểu 5 ký tự mô tả rõ ràng năng lực người học."
                )
        return v

    @field_validator("test_cases")
    @classmethod
    def validate_test_cases(cls, v: list[TestCase]) -> list[TestCase]:
        if not v or len(v) == 0:
            raise ValueError(
                "Mỗi bài tập bắt buộc phải có ít nhất 1 test case kiểm chứng theo tiêu chí DoD!"
            )
        return v


class ExerciseDraft(ExerciseBase):
    """Draft exercise generated by AI, pending human review (DoD: no auto-publishing)."""

    status: Literal[
        "draft_pending_review",
        "approved",
        "revision_requested",
        "rejected",
        "published",
    ] = Field(
        "draft_pending_review",
        description="Trạng thái bài tập. Mặc định luôn là draft_pending_review (DoD: Tuyệt đối không tự publish)",
    )
    review_round: int = Field(
        1, ge=1, le=2, description="Vòng kiểm duyệt hiện tại (tối đa 2 vòng)"
    )
    review_notes: str | None = Field(
        None, description="Nhận xét của Giảng viên / Reviewer con người"
    )
    created_at: str = Field(
        default_factory=lambda: datetime.utcnow().isoformat() + "Z",
        description="Thời điểm AI tạo bản nháp",
    )
    updated_at: str = Field(
        default_factory=lambda: datetime.utcnow().isoformat() + "Z",
        description="Thời điểm cập nhật gần nhất",
    )
    similarity_score: float = Field(
        0.0,
        description="Điểm tương đồng lớn nhất so với ngân hàng câu hỏi hiện có (0.0 đến 1.0)",
    )
    is_duplicate: bool = Field(False, description="Cờ cảnh báo trùng lặp (> 0.70)")
    is_feasible: bool = Field(
        True, description="Cờ xác nhận đáp án chạy khả thi trên dữ liệu thực tế"
    )
    is_calibrated: bool = Field(
        True, description="Cờ xác nhận độ khó và cấp độ Bloom hợp lệ"
    )


class ExerciseApproved(ExerciseDraft):
    """Approved exercise that passed human review and quality verification."""

    reviewer_id: str = Field(
        ..., description="Mã định danh Giảng viên / Reviewer phê duyệt"
    )
    approved_at: str = Field(
        default_factory=lambda: datetime.utcnow().isoformat() + "Z",
        description="Thời điểm phê duyệt",
    )


class ExerciseGenerateRequest(BaseModel):
    """Request payload to invoke AI Exercise Generator."""

    dataset_id: str = Field(..., description="Mã dataset nguồn (vd: retail_sales_v1)")
    bloom_level: (
        Literal["Remember", "Understand", "Apply", "Analyze", "Evaluate", "Create"]
        | None
    ) = Field(
        None,
        description="Cấp độ Bloom mong muốn (để trống nếu muốn AI tự động đề xuất đa dạng)",
    )
    difficulty: Literal["Beginner", "Intermediate", "Advanced"] | None = Field(
        None, description="Độ khó mong muốn"
    )
    exercise_type: Literal["SQL", "Python", "Data Analysis"] = Field(
        "SQL", description="Loại bài tập mong muốn sinh"
    )
    count: int = Field(1, ge=1, le=5, description="Số lượng bản nháp cần sinh")


class ExerciseFilterRequest(BaseModel):
    """Filter parameters for querying exercises."""

    dataset_id: str | None = None
    bloom_level: str | None = None
    difficulty: str | None = None
    status: str | None = None
    exercise_type: str | None = None
    keyword: str | None = None
